name: Déploiement via SSH et Git Pull

on:
  push:
    branches:
      - main # Déclenche le workflow à chaque push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connexion au serveur et Git Pull
        uses: actions/checkout@v4
        echo 'hello world'
