name: Déploiement automatique

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Déploiement sur Alwaysdata avec SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh-mbroumsadja.alwaysdata.net
          username: mbroumsadja
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rsync -avz --delete /github/workspace/ /home/mbroumsadja/send_file_speedly/
