name : deployement automatique

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: recuperation du code 
              uses: actions/checkout@v4
            
            - name: config ssh
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan ssh-mbroumsadja.alwaysdata.net >> ~/.ssh/known_hosts
            - name: synchronisation avec mon serveur
              run: |
                rsync -avz --delete ./ton_dossier_local/ \
                mbroumsadja@ssh-mbroumsadja.alwaysdata.net:/home/mbroumsadja/send_file_speedly/