name: Deploy to AlwaysData

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer la clé SSH
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh.alwaysdata.com >> ~/.ssh/known_hosts

      # Étape 3 : Synchroniser le dossier avec AlwaysData via SCP
      - name: Deploy to AlwaysData
        run: |
          scp -r ./path/to/your/folder user@ssh.alwaysdata.com:/path/to/remote/folder